In [49]:
import requests
import time
from bs4 import BeautifulSoup as BS
import pandas as pd

In [108]:
1000%1010 == 0

False

In [102]:
test_url = "http://web.legabasket.it/game/64173/cimberio_varese-montepaschi_siena_87-86"
req = requests.get(test_url)
soup = BS(req.text, 'lxml')

partita = test_url.split('.it')[-1]

In [127]:
short_columns = ['Squadra','Tit','#','Giocatore','Pts','Min','FC','FS','2P','2PA','2P%','SCH','3P','3PA','3P%',
                 'TL','TLA','TL%','DREB','OREB','TREB','BLKD','BLKS','PP','PR','AST','Val Lega','OER','+/-']
print(len(short_columns), len(columns))

29 30

In [103]:
columns = ['Partita','Squadra','Titolare','Numero','Giocatore','Punti',
           'Minuti','Falli Commessi','Falli Subiti',
           'Tiri da 2 Realizzati','Tiri da 2 Tentati',
           '% da 2','Schiacciate','Tiri da 3 Realizzati',
           'Tiri da 3 Tentati','% da 3','Tiri Liberi Realizzati',
           'Tiri da Liberi Tentati','% Liberi','Rimbalzi Dif',
           'Rimbalzi Off','Rimbalzi Tot','Stoppate Date',
           'Stoppate Subite','Palle Perse','Palle Recuperate',
           'Assist','Valutazione Lega','Valutazione OER','+/-']

games_df = pd.DataFrame(columns=columns)

In [104]:
tables = soup.findAll('table')[1:3]

In [105]:
pos = 0
for table in tables:
    for i, tr in enumerate(table.findAll('tr')):
        this_row = [partita]
        if i == 0:
            team = tr.findAll('th')[0].text
            continue
        if i == 1:
            continue
        this_row.append(team)
        for td in tr.findAll('td'):
            this_row.append(td.get_text().strip())

        games_df.loc[pos] = this_row
        pos += 1

In [106]:
games_df

,Partita,Squadra,Titolare,Numero,Giocatore,Punti,Minuti,Falli Commessi,Falli Subiti,Tiri da 2 Realizzati,...,Rimbalzi Off,Rimbalzi Tot,Stoppate Date,Stoppate Subite,Palle Perse,Palle Recuperate,Assist,Valutazione Lega,Valutazione OER,+/-
0,/game/3952/pinti_inox_roma-prandoni_bergamo_73-67,Pinti Inox Roma,,,Squadra,,0,,,0,...,,0,0,0,,,0,0,0.00,
1,/game/3952/pinti_inox_roma-prandoni_bergamo_73-67,Pinti Inox Roma,,,Totali,,,0,0,,...,0,0,,,0,0,,0,,
2,/game/3952/pinti_inox_roma-prandoni_bergamo_73-67,Prandoni Bergamo,,,Squadra,,0,,,0,...,,0,0,0,,,0,0,0.00,
3,/game/3952/pinti_inox_roma-prandoni_bergamo_73-67,Prandoni Bergamo,,,Totali,0,0,0,0,0,...,0,0,0,0,0,0,0,0,,

In [101]:
games_df.to_csv('./out_data/test_game.csv', index=False)

In [128]:
df_pick = pd.read_pickle('./out_data/games_details/games_details_raw_5700.pkl')
df_pick['Punti'] = df_pick['Punti'].astype(int)
df_pick[(df_pick['Squadra'].str.contains('Varese')) & (df_pick['Giocatore'] != 'Totali')].sort_values('Punti', ascending=False)

,Partita,Squadra,Titolare,Numero,Giocatore,Punti,Minuti,Falli Commessi,Falli Subiti,Tiri da 2 Realizzati,...,Rimbalzi Off,Rimbalzi Tot,Stoppate Date,Stoppate Subite,Palle Perse,Palle Recuperate,Assist,Valutazione Lega,Valutazione OER,+/-
59624,/game/54589/a__ranger_varese-fernet_branca_pav...,A. Ranger Varese,*,0,Theus Reggie,50,40,1,9,12,...,3,4,0,0,8,2,10,54,1.18,0
99769,/game/56277/cagiva_varese-madigan_pistoia_112-100,Cagiva Varese,*,0,Komazec Arijan,46,40,4,10,9,...,9,10,0,1,2,2,6,61,1.61,0
61880,/game/54995/a__ranger_varese-billy_desio_103-84,A. Ranger Varese,*,0,Theus Reggie,46,37,2,13,6,...,2,5,1,0,1,2,3,53,1.37,0
100750,/game/56284/cagiva_varese-meta_system_r_emilia...,Cagiva Varese,*,0,Komazec Arijan,44,38,3,3,9,...,2,3,1,0,4,3,8,50,1.60,0
97802,/game/56215/cagiva_varese-panapesca_montecatin...,Cagiva Varese,*,0,Komazec Arijan,44,39,4,7,11,...,2,3,0,0,4,3,4,49,1.57,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76891,/game/55348/hyundai_desio-cagiva_varese_71-67,Cagiva Varese,,0,Biganzoli Daniele,0,5,1,0,0,...,0,0,0,0,0,0,0,-2,0.00,0
76890,/game/55348/hyundai_desio-cagiva_varese_71-67,Cagiva Varese,,0,Conti Andrea,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
76490,/game/55473/mangiaebevi_bologna-cagiva_varese_...,Cagiva Varese,,,Squadra,0,0,0,1,0,...,2,4,0,0,3,4,0,6,0.00,
76485,/game/55473/mangiaebevi_bologna-cagiva_varese_...,Cagiva Varese,,0,DiÂ Sabato Mario,0,5,1,0,0,...,0,0,0,0,1,0,0,-2,0.00,0
136744,/game/57694/pall__varese-calze_pompea_roma_74-57,Pall. Varese,,,Squadra,0,0,0,0,0,...,2,2,0,0,0,1,0,3,0.00,

In [129]:
df_pick[(df_pick['Squadra'].str.contains('Varese'))]

,Partita,Squadra,Titolare,Numero,Giocatore,Punti,Minuti,Falli Commessi,Falli Subiti,Tiri da 2 Realizzati,...,Rimbalzi Off,Rimbalzi Tot,Stoppate Date,Stoppate Subite,Palle Perse,Palle Recuperate,Assist,Valutazione Lega,Valutazione OER,+/-
180,/game/52246/dietor_bologna-divarese_varese_84-82,Divarese Varese,*,0,Boselli Dino,0,19,2,1,0,...,0,0,0,0,2,3,0,-1,0.00,0
181,/game/52246/dietor_bologna-divarese_varese_84-82,Divarese Varese,*,0,Thompson Corny,34,37,2,7,14,...,7,11,1,0,4,3,0,40,1.17,0
182,/game/52246/dietor_bologna-divarese_varese_84-82,Divarese Varese,,0,Castaldini Gianluca,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
183,/game/52246/dietor_bologna-divarese_varese_84-82,Divarese Varese,,0,Ferraiuolo Massimo,6,21,1,1,2,...,1,2,0,1,0,1,2,7,1.00,0
184,/game/52246/dietor_bologna-divarese_varese_84-82,Divarese Varese,,0,Curtarello Guido,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136741,/game/57694/pall__varese-calze_pompea_roma_74-57,Pall. Varese,,0,Casoli Roberto,2,15,4,2,0,...,4,6,0,0,3,2,0,4,0.40,0
136742,/game/57694/pall__varese-calze_pompea_roma_74-57,Pall. Varese,,0,DeÂ Pol Alessandro,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
136743,/game/57694/pall__varese-calze_pompea_roma_74-57,Pall. Varese,,0,Lokhmanchuk Olexander,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
136744,/game/57694/pall__varese-calze_pompea_roma_74-57,Pall. Varese,,,Squadra,0,0,0,0,0,...,2,2,0,0,0,1,0,3,0.00,
136745,/game/57694/pall__varese-calze_pompea_roma_74-57,Pall. Varese,,,Totali,74,200,21,17,20,...,26,40,6,0,15,15,15,96,0.90,

In [130]:
len(df_pick)

136758

In [138]:
done_games_df

,Partita,Squadra,Titolare,Numero,Giocatore,Punti,Minuti,Falli Commessi,Falli Subiti,Tiri da 2 Realizzati,...,Rimbalzi Off,Rimbalzi Tot,Stoppate Date,Stoppate Subite,Palle Perse,Palle Recuperate,Assist,Valutazione Lega,Valutazione OER,+/-
0,/game/52194/basket_brescia-dietor_bologna_81-92,Basket Brescia,*,0,Gilardi Enrico,11,37,3,2,3,...,5,5,0,0,4,3,6,11,0.63,0
1,/game/52194/basket_brescia-dietor_bologna_81-92,Basket Brescia,*,0,Sitton Charlie,24,38,2,5,10,...,5,9,0,0,2,5,0,30,1.07,0
2,/game/52194/basket_brescia-dietor_bologna_81-92,Basket Brescia,,0,Portesani Pierluigi,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
3,/game/52194/basket_brescia-dietor_bologna_81-92,Basket Brescia,,0,Cavazzana Vincenzo,0,3,1,0,0,...,0,1,0,0,0,0,0,0,0.00,0
4,/game/52194/basket_brescia-dietor_bologna_81-92,Basket Brescia,,0,Brocchi Oscar,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136753,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Pessina Davide,6,22,2,3,1,...,2,5,0,2,2,4,1,9,0.67,0
136754,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Carera Flavio,17,28,4,5,6,...,2,5,0,1,2,1,1,18,1.21,0
136755,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Nickerson Gaylon,3,29,4,0,0,...,3,3,0,0,3,3,1,0,0.43,0
136756,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,,,Squadra,0,0,0,0,0,...,2,2,0,0,1,3,0,4,0.00,
136757,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,,,Totali,57,200,17,21,15,...,18,30,0,6,14,16,6,53,0.71,

In [137]:
import os
all_pickles = os.listdir('./out_data/games_details/')
all_pickles.sort()
max_pickle = all_pickles[-1]
done_games_df = pd.read_pickle('./out_data/games_details/' + max_pickle)

In [140]:
count = int(max_pickle.split('.')[0].split('_')[-1])
print(count)

5700

In [151]:
done_games_5600 = pd.read_pickle('./out_data/games_details/games_details_raw_5600.pkl')
done_games_5700 = pd.read_pickle('./out_data/games_details/games_details_raw_5700.pkl')
done_games_5800 = pd.read_pickle('./out_data/games_details/games_details_raw_5800.pkl')

In [152]:
print(done_games_5600.shape[0], done_games_5700.shape[0], done_games_5800.shape[0])

134358 136758 139156

In [154]:
done_games_5700.tail()

,Partita,Squadra,Titolare,Numero,Giocatore,Punti,Minuti,Falli Commessi,Falli Subiti,Tiri da 2 Realizzati,...,Rimbalzi Off,Rimbalzi Tot,Stoppate Date,Stoppate Subite,Palle Perse,Palle Recuperate,Assist,Valutazione Lega,Valutazione OER,+/-
136753,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Pessina Davide,6,22,2,3,1,...,2,5,0,2,2,4,1,9,0.67,0
136754,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Carera Flavio,17,28,4,5,6,...,2,5,0,1,2,1,1,18,1.21,0
136755,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Nickerson Gaylon,3,29,4,0,0,...,3,3,0,0,3,3,1,0,0.43,0
136756,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,,,Squadra,0,0,0,0,0,...,2,2,0,0,1,3,0,4,0.00,
136757,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,,,Totali,57,200,17,21,15,...,18,30,0,6,14,16,6,53,0.71,

In [155]:
done_games_5800.loc[136755:136760,:]

,Partita,Squadra,Titolare,Numero,Giocatore,Punti,Minuti,Falli Commessi,Falli Subiti,Tiri da 2 Realizzati,...,Rimbalzi Off,Rimbalzi Tot,Stoppate Date,Stoppate Subite,Palle Perse,Palle Recuperate,Assist,Valutazione Lega,Valutazione OER,+/-
136755,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,*,0,Nickerson Gaylon,3,29,4,0,0,...,3,3,0,0,3,3,1,0,0.43,0
136756,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,,,Squadra,0,0,0,0,0,...,2,2,0,0,1,3,0,4,0.00,
136757,/game/57694/pall__varese-calze_pompea_roma_74-57,Calze Pompea Roma,,,Totali,57,200,17,21,15,...,18,30,0,6,14,16,6,53,0.71,
136758,/game/57700/calze_pompea_roma-benetton_treviso...,Calze Pompea Roma,,0,Magnifico Walter,9,22,2,3,3,...,3,5,0,0,1,1,1,12,1.00,0
136759,/game/57700/calze_pompea_roma-benetton_treviso...,Calze Pompea Roma,*,0,Obradovic Sasa,14,34,2,8,4,...,2,6,1,2,4,7,2,19,0.76,0
136760,/game/57700/calze_pompea_roma-benetton_treviso...,Calze Pompea Roma,,0,Fiasco Ruggero,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.00,0

In [159]:
done_games_6100 = pd.read_pickle('./out_data/games_details/games_details_raw_6100.pkl')
done_games_6100.groupby('Partita').aggregate({'Squadra':'count'}).reset_index().sort_values('Squadra')

                                                Partita  Squadra
5473  /game/57664/b__sardegna_sassari-jcoplastic_nap...       22
4324  /game/56515/tonno_auriga_trapani-libertas_udin...       23
2184  /game/54373/teorematour_arese-turboair_fabrian...       23
616   /game/52804/cantine_riunite_r_emilia-arimo_bol...       23
4211  /game/56402/pfizer_reggio_calabria-panapesca_m...       23
...                                                 ...      ...
2032    /game/54221/emmezeta_udine-corona_cremona_86-79       24
2031  /game/54220/fernet_branca_pavia-lotus_montecat...       24
2030  /game/54219/kleenex_pistoia-tombolini_livorno_...       24
2039  /game/54228/teorematour_arese-ticino_assicuraz...       24
6099  /game/58350/teamsystem_bologna-benetton_trevis...       24

[6100 rows x 2 columns]

In [167]:
all_pickles = [x for x in os.listdir('./out_data/games_details/') if '.pkl' in x]
pickle_numbers = [int(x.split('.')[0].split('_')[-1]) for x in all_pickles]
max_pickle_number = max(pickle_numbers)
max_pickle = [x for x in all_pickles if str(max_pickle_number) in x][0]

11400
games_details_raw_11400.pkl

In [162]:
x.split('.')[0].split('_')[-1]

NameError: name 'x' is not defined